name: Deploy to GitHub Pages

env:
  SPHINX_SOURCEDIR: src
  SPHINX_OUTPUTDIR: generated

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  generate-upload-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Setup Poetry
        run: |
          pip3 install --user poetry==1.1.14
          python -m poetry config --local virtualenvs.in-project true

      - name: Cache virtual environment
        id: cache-venv
        uses: actions/cache@v2
        with:
          path: .venv
          key: ${{ runner.os }}-${{ hashFiles('pyproject.toml') }}

      - name: Setup virtual environment
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          poetry install -v

      - name: Generate pages
        run: |
          python -m poetry run sphinx-build -b html ${SPHINX_SOURCEDIR}/ ${SPHINX_OUTPUTDIR}/

      - name: Upload pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ${SPHINX_OUTPUTDIR}/

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@main
