name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate pages
        run: |
          mkdir build
          cp -r src/* build/
          echo Done

      - name: Prepare deployment branch
        env:
          GITHUB_DEPLOYMENT_BRANCH: cppsmith-github-io
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@github"
          git stash push --include-untracked build/
          git fetch
          git checkout ${GITHUB_DEPLOYMENT_BRANCH}
          rm -rf *
          git stash pop
          touch .nojekyll
          mv build/* .

      - name: Deploy
        run: |
          git add --all
          commit_origin_date=$(git log -1 --pretty=%ct)
          commit_subject="Deploy using `echo ${GITHUB_SHA} | cut -c1-8` made on `date -d\"@${commit_origin_date}\" --iso-8601=seconds`"
          git commit --message="${commit_subject}"
          git push
